### ISSUE TITLE
Undefined method 'split' for nil class

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#145]

**Comment by kirkkwang** [comment]
stack trace locally

```
[ActiveJob] [CreateDerivativesJob] [8dfff7f2-de0d-453a-9e6f-a24c03f22cb1] Error performing CreateDerivativesJob (Job ID: 8dfff7f2-de0d-453a-9e6f-a24c03f22cb1) from GoodJob(default) in 95.34ms: NoMethodError (undefined method `split' for nil:NilClass):
/usr/local/bundle/gems/derivative-rodeo-0.5.3/lib/derivative_rodeo/storage_locations/base_location.rb:66:in `from_uri'
/usr/local/bundle/bundler/gems/iiif_print-c6b566e6c435/app/services/iiif_print/derivative_rodeo_service.rb:361:in `input_uri'
/usr/local/bundle/bundler/gems/iiif_print-c6b566e6c435/app/services/iiif_print/derivative_rodeo_service.rb:331:in `rescue in lasso_up_some_derivatives'
/usr/local/bundle/bundler/gems/iiif_print-c6b566e6c435/app/services/iiif_print/derivative_rodeo_service.rb:323:in `lasso_up_some_derivatives'
/usr/local/bundle/bundler/gems/iiif_print-c6b566e6c435/app/services/iiif_print/derivative_rodeo_service.rb:269:in `block in create_derivatives'
/usr/local/bundle/bundler/gems/iiif_print-c6b566e6c435/app/services/iiif_print/derivative_rodeo_service.rb:268:in `each'
/usr/local/bundle/bundler/gems/iiif_print-c6b566e6c435/app/services/iiif_print/derivative_rodeo_service.rb:268:in `flat_map'
/usr/local/bundle/bundler/gems/iiif_print-c6b566e6c435/app/services/iiif_print/derivative_rodeo_service.rb:268:in `create_derivatives'
/usr/local/bundle/gems/hyrax-3.5.0/app/models/concerns/hyrax/file_set/derivatives.rb:52:in `create_derivatives'
/usr/local/bundle/gems/hyrax-3.5.0/app/jobs/create_derivatives_job.rb:12:in `perform'
/app/samvera/app/jobs/create_derivatives_job_decorator.rb:8:in `perform'
/usr/local/bundle/gems/activejob-5.2.8.1/lib/active_job/execution.rb:39:in `block in perform_now'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/usr/local/bundle/gems/i18n-1.14.1/lib/i18n.rb:322:in `with_locale'
/usr/local/bundle/gems/activejob-5.2.8.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-5.2.8.1/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/bundle/gems/activejob-5.2.8.1/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/usr/local/bundle/gems/activejob-5.2.8.1/lib/active_job/logging.rb:46:in `block in tag_logger'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/tagged_logging.rb:71:in `tagged'
/usr/local/bundle/gems/activejob-5.2.8.1/lib/active_job/logging.rb:46:in `tag_logger'
/usr/local/bundle/gems/activejob-5.2.8.1/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/bundle/gems/activejob-5.2.8.1/lib/active_job/execution.rb:38:in `perform_now'
/app/samvera/hyrax-webapp/lib/active_job_tenant.rb:38:in `block in perform_now'
/app/samvera/hyrax-webapp/lib/active_job_tenant.rb:57:in `block in switch'
/usr/local/bundle/gems/apartment-2.2.1/lib/apartment/adapters/abstract_adapter.rb:85:in `switch'
/usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `switch'
/app/samvera/hyrax-webapp/lib/active_job_tenant.rb:56:in `switch'
/app/samvera/hyrax-webapp/lib/active_job_tenant.rb:37:in `perform_now'
/usr/local/bundle/gems/sentry-rails-5.16.1/lib/sentry/rails/active_job.rb:9:in `block in perform_now'
/usr/local/bundle/gems/sentry-rails-5.16.1/lib/sentry/rails/active_job.rb:35:in `block in record'
/usr/local/bundle/gems/sentry-ruby-5.16.1/lib/sentry/hub.rb:59:in `with_scope'
/usr/local/bundle/gems/sentry-ruby-5.16.1/lib/sentry-ruby.rb:371:in `with_scope'
/usr/local/bundle/gems/sentry-rails-5.16.1/lib/sentry/rails/active_job.rb:23:in `record'
/usr/local/bundle/gems/sentry-rails-5.16.1/lib/sentry/rails/active_job.rb:8:in `perform_now'
/usr/local/bundle/gems/activejob-5.2.8.1/lib/active_job/execution.rb:24:in `block in execute'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-5.2.8.1/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/execution_wrapper.rb:90:in `wrap'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/reloader.rb:73:in `block in wrap'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/execution_wrapper.rb:86:in `wrap'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/reloader.rb:72:in `wrap'
/usr/local/bundle/gems/activejob-5.2.8.1/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/bundle/gems/activejob-5.2.8.1/lib/active_job/execution.rb:22:in `execute'
/usr/local/bundle/gems/good_job-2.99.0/lib/models/good_job/execution.rb:351:in `block (2 levels) in execute'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/bundle/gems/good_job-2.99.0/lib/models/good_job/execution.rb:350:in `block in execute'
/usr/local/bundle/gems/good_job-2.99.0/lib/good_job/current_thread.rb:84:in `within'
/usr/local/bundle/gems/good_job-2.99.0/lib/models/good_job/execution.rb:345:in `execute'
/usr/local/bundle/gems/good_job-2.99.0/lib/models/good_job/execution.rb:246:in `perform'
/usr/local/bundle/gems/good_job-2.99.0/lib/models/good_job/execution.rb:162:in `block in perform_with_advisory_lock'
/usr/local/bundle/gems/good_job-2.99.0/lib/models/good_job/lockable.rb:163:in `block in with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/scoping/default.rb:34:in `block in unscoped'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/relation.rb:281:in `scoping'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/scoping/default.rb:34:in `unscoped'
/usr/local/bundle/gems/good_job-2.99.0/lib/models/good_job/lockable.rb:163:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/relation/delegation.rb:97:in `block in with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/relation.rb:281:in `scoping'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/relation/delegation.rb:97:in `with_advisory_lock'
/usr/local/bundle/gems/good_job-2.99.0/lib/models/good_job/execution.rb:157:in `perform_with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/relation/delegation.rb:97:in `block in perform_with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/relation.rb:281:in `scoping'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/relation/delegation.rb:97:in `perform_with_advisory_lock'
/usr/local/bundle/gems/good_job-2.99.0/lib/good_job/job_performer.rb:27:in `next'
/usr/local/bundle/gems/good_job-2.99.0/lib/good_job/scheduler.rb:270:in `block (2 levels) in create_task'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/execution_wrapper.rb:90:in `wrap'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/reloader.rb:73:in `block in wrap'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/execution_wrapper.rb:90:in `wrap'
/usr/local/bundle/gems/activesupport-5.2.8.1/lib/active_support/reloader.rb:72:in `wrap'
/usr/local/bundle/gems/good_job-2.99.0/lib/good_job/scheduler.rb:269:in `block in create_task'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/scheduled_task.rb:298:in `process_task'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/timer_set.rb:165:in `block (2 levels) in process_tasks'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
```

**Comment by ShanaLMoore** [comment]
@kirkkwang locally, does this work not have a thumbnail too, from the works index page?

**Comment by kirkkwang** [comment]
@ShanaLMoore correct, because a thumbnail is a derivative and the create derivative job didn't work correctly

**Comment by ShanaLMoore** [comment]
Is this still an issue?

**Comment by KatharineV** [comment]
I tested with my own 6 page PDF. 

https://adl.s2.adventistdigitallibrary.org/concern/generic_works/538a6bcf-e2b7-429e-b15a-f19530a9a7d9?locale=en

BUGS:
The splitting worked, but we have double the number of child works showing in the items list. On Production we usually only see the child works with page numbers attached. However, on staging, there are a string of JPEGs in the item list.

All child works are showing in the UV, so the work is duplicated in the UV.

**Comment by ShanaLMoore** [comment]
@KatharineV Would you mind if we create a separate issue for the duplicate children? It seems like the original issue is solved.

**Comment by KatharineV** [comment]
That makes sense
________________________________

**Comment by ShanaLMoore** [comment]
Also, how would you prioritize it? A must solve before cutover or can it wait? @KatharineV

**Comment by KatharineV** [comment]
Great question. It's medium-high priority because the duplication of the work in the UV is illogical and will drive our users crazy, not to mention it will be very unweildy with our longer works. We have thousand page PDFs sometimes, and we want to rely on the UV as our primary viewer (although we could turn it off long enough to get the 80,000+ periodicals imported from the OAI feed).

Did this issue not happen when you folks were testing? Am I the first one to see it? If so, is it possible that I'm doing something that is causing the duplication of child works and in the UV??? Eek!
________________________________

**Comment by ShanaLMoore** [comment]
@KatharineV No, there is a bug reported in Hyrax so it's probably not just your application that it's happening to.

**Comment by KatharineV** [comment]
We've given up on the UV, so this ticket isn't relevant anymore. I'm passing it to the Done column.
